### ISSUE TITLE
examples of how to customise the list of maildirs

### ISSUE THREAD

**Issue by emacsomancer** [agpchil/mu4e-maildirs-extension#18]
I see that there is customisable "mu4e-maildirs-extension-custom-list", which I assume is how one would control which maildirs are shown, and which subdirectories are shown.  Can you provide an example of how to do this?

**Comment by agpchil** [comment]
Sorry for the late reply!
It looks like I removed the examples for this at some point :(

Anyway, `mu4e-maildirs-extension-custom-list` has the same format as the output of `(mu4e-get-maildirs)`.

You can set it directly with something like this:

```
(setq mu4e-maildirs-extension-custom-list
      '("/account1/INBOX"
        "/account2/INBOX"))
```

Or using customize `M-x customize-option`.

**Comment by emacsomancer** [comment]
Thanks, I got it to work via (setq...), I'm not sure of the syntax for
the M-x customise route.

**Comment by agpchil** [comment]
I'm glad it worked! :)
In the `M-x customize` you need to insert strings (using the INS button for adding elements to the list) and then save or apply that customization. But maybe `setq` is easier :)

I'll close this once I fixed the documentation.
Feel free to open new issues if you have more questions or problems!
