### ISSUE TITLE
Wrong type argument issue with the new version

### ISSUE THREAD

**Issue by cryoguy** [agpchil/mu4e-maildirs-extension#19]
I can not seem to implemente Write your own maildir format handler.  Got following error:

error in process filter: propertize: Wrong type argument: numberp, nil
error in process filter: Wrong type argument: numberp, nil

Any thoughts?  Thank for the great work.

Tony
--------------------------------------------
Memory Imprint Studio

**Comment by agpchil** [comment]
Ouch! I think the snippet in the README won't work in the `master` branch. That's because `:unread` and `:total` data are `nil` while the data is being fetch async. I'll try to fix that example.

What do you want to customize using the custom handler?

You can change some of the maildir format using `mu4e-maildirs-extension-maildir-format` and other variables. But documentation is clearly lacking here.

**Comment by cryoguy** [comment]
Thanks for your quick reply.   I just want to do some simple formatting so that the unread /total standing out in  mu4e-main frame.  No rush.

Tony

**Comment by agpchil** [comment]
Sorry for the late reply!

I recommend to use `mu4e-maildirs-extension-maildir-format` and `mu4e-maildirs-extension-maildir-hl-regex` for basic formatting (It's still somewhat limited but should work for simple stuff). 

Anyway, the following example for the maildir format handler should work with master version:

```lisp
(defun my/mu4e-maildirs-extension-propertize-unread-only (item)
        "Propertize only the maildir unread count using ITEM plist."
        (let ((unread (or (plist-get item :unread) 0))
              (total (or (plist-get item :total) 0)))
          (format "\t%s%s %s (%s/%s)"
                  (plist-get item :indent)
                  (plist-get item :prefix)
                  (plist-get item :name)
                  (propertize (number-to-string unread)
                              'face (cond
                                     ((> unread 0) 'mu4e-maildirs-extension-maildir-hl-face)
                                     (t            'mu4e-maildirs-extension-maildir-face)))
                  total)))
```

You can set it with:

```lisp
 (setq mu4e-maildirs-extension-propertize-func 'my/mu4e-maildirs-extension-propertize-unread-only))
```

**Comment by cryoguy** [comment]
Thanks, works now!      Tony
