### ISSUE TITLE
Include mu4e configuration in README

### ISSUE THREAD

**Issue by nwolfe** [agpchil/mu4e-maildirs-extension#21]
I think it would be helpful to show the corresponding mail directory layout and elisp configuration that produced the screenshot in the README.

I'm having trouble getting mu4e to render the account maildir trees properly. I can fudge some mu4e configuration to make it visually appear correct, but then that breaks the query and always just reads `(0/0)`.

I want it to look like the screenshot in the README, but I only have 1 email account for the time being.
@agpchil - how would you recommend I change my setup so it renders properly? Not sure where I went wrong.

Here's what mine looks like:
<img width="345" alt="screen shot 2015-12-01 at 10 11 44 am" src="https://cloud.githubusercontent.com/assets/1787615/11510096/bd34848a-9816-11e5-997b-6bf921bbbd44.png">

My maildir directory layout:
```
Mail
|-- Work
    |-- archive
    |-- drafts
    |-- sent
    `-- trash
|-- Personal
    |-- archive
    |-- drafts
    |-- sent
    `-- trash
```

My relevant elisp configuration:
```elisp
  (setq mu4e-maildir "~/Mail/Work")
  (setq mu4e-drafts-folder "/drafts")
  (setq mu4e-sent-folder "/sent")
  (setq mu4e-trash-folder "/trash")
  (setq mu4e-maildir-shortcuts
        '(("/archive" . ?a)
          ("/sent"    . ?s)
          ("/trash"   . ?t)
          ("/drafts"  . ?d)))
```
(No custom bookmarks, just mu4e default ones for now)

My offlineimaprc:
```conf
[general]
accounts = Work
maxsyncaccounts = 3
pythonfile = ~/.offlineimap.py

[Account Work]
localrepository = Work-Local
remoterepository = Work-Remote

[Repository Work-Local]
type = Maildir
localfolders = ~/Mail/Work
nametrans = lambda folder: {'drafts':  '[Gmail]/Drafts',
                            'sent':    '[Gmail]/Sent Mail',
                            'trash':   '[Gmail]/Trash',
                            'archive': '[Gmail]/All Mail'
                            }.get(folder, folder)

[Repository Work-Remote]
type = Gmail
remotehost = imap.gmail.com
remoteuser = xxxxxxxxxx 
remotepasseval = get_authinfo_pass('imap.gmail.com', 'xxxxxxxxxx')
ssl = yes
maxconnections = 1
realdelete = no
sslcacertfile = /usr/local/etc/openssl/osx_cert.pem
nametrans = lambda folder: {'[Gmail]/Drafts':    'drafts',
                            '[Gmail]/Sent Mail': 'sent',
                            '[Gmail]/Trash':     'trash',
                            '[Gmail]/All Mail':  'archive'
                            }.get(folder, folder)
folderfilter = lambda folder: folder in ['[Gmail]/All Mail',
                                         '[Gmail]/Drafts',
                                         '[Gmail]/Sent Mail',
                                         '[Gmail]/Trash']
```

**Comment by agpchil** [comment]
Looks like I removed the docs for the directory structure from the README in a previous commit :(
The docs are clearly lacking but I don't think much configuration is needed to make this work. But  feel free to improve them and send me a PR if you want! :)

Directory structure in ~/Mail/

```
account1/
  inbox/
  drafts/
  ...
account2/
  inbox/
  drafts/
  ...
```

and index with mu:

```
mu index --mail=~/Mail/
```

(Note: I'm not sure about this but I think if you already indexed the `~/Mail/` directory before maybe you'll need to remove the ~/.mu database and reindex again.)

I'm a bit unsure about the following setting:
```lisp
(setq mu4e-maildir "~/Mail/Work")
```

Maybe it should be `~/Mail/` instead?

**Comment by agpchil** [comment]
Ouch, typo. The mu command should be:
```
mu index --maildir=~/Mail/
```

**Comment by nwolfe** [comment]
> Maybe it should be ~/Mail/ instead?

Ok, I tried what you suggested and changed this to be `~/Mail/` instead, blew away ~/.mu, and did `mu index --maildir=~/Mail/`.  I then set the following:
```elisp
  (setq mu4e-maildir "~/Mail")
  (setq mu4e-drafts-folder "/Work/drafts")
  (setq mu4e-sent-folder "/Work/sent")
  (setq mu4e-trash-folder "/Work/trash")
  (setq mu4e-maildir-shortcuts
        '(("/Work/archive" . ?a)
          ("/Work/sent"    . ?s)
          ("/Work/trash"   . ?t)
          ("/Work/drafts"  . ?d)))
```

(As an aside, not sure how hardcoding `mu4e-{drafts,sent,trash}-folder` to a particular account like `/Work/` will really work when I actually have multiple accounts, but I probably don't have this part quite correct)

I didn't change anything in my .offlineimaprc - the local Work repository is set to `localfolders = ~/Mail/Work`.

Nothing seems to have changed though in the mu4e UI though :(

**Comment by nwolfe** [comment]
Wait...I went to lunch and tried again and now it is correctly rendering the account/maildirs tree! I blame caching somewhere :smile: 

I'm still not sure how I will address the hardcoded `mu4e-{drafts,sent,trash}-folder`s.
@agpchil I was hoping to find your `dotfiles` repo so I could peak at your configuration but I don't see one on GitHub...how do you configure these three directories if you have multiple accounts?

**Comment by agpchil** [comment]
I'm glad it's working! :)
Sorry, I don't have my dotfiles published... (yet?)

You can find how to setup for multiple accounts in the official mu manual:
http://www.djcbsoftware.nl/code/mu/mu4e/Multiple-accounts.html

Also be sure to check the mu mailing-list:
https://groups.google.com/forum/#!forum/mu-discuss

(I believe there was a few topics about multiple accounts already)

**Comment by nwolfe** [comment]
Thank you for the multiple accounts link! I believe I've got it all working as desired now, though I haven't actually added a secondary account yet (just wanted to support multiples from the start).

**Comment by agpchil** [comment]
Nice :)

I'll leave this issue open until I restore the docs in the README

**Comment by agpchil** [comment]
I restored the `Directory structure` section in the README.
