### ISSUE TITLE
mu4e-maildirs-extension-custom-list changes only effected at emacs restart

### ISSUE THREAD

**Issue by deepfire** [agpchil/mu4e-maildirs-extension#30]
Changing `mu4e-maildirs-extension-custom-list changes` has no visible effect until Emacs is restarted -- even `mu4e` restart has no effect.

**Comment by agpchil** [comment]
The data is cached until the updated index hook is triggered. To clear the cache and refresh you need to press `C-u C-u u` in the mu4e main buffer.

**Comment by deepfire** [comment]
@agpchil, this does not seem to correlate with my observations -- `mu4e-update-mail-and-index` certainly doesn't lead to refresh.  Is that the problem?

**Comment by agpchil** [comment]
I can't look at this now, but IIRC `mu4e-index-updated-hook` is only called if a message has been updated from the index. Not sure why you mention `mu4e-update-mail-and-index` function. Can you confirm if using `C-u C-u u` works for you?

**Comment by deepfire** [comment]
@agpchil, the reason I mention `mu4e-update-mail-and-index` is UI-related.

As I see it (please, feel free to correct me), _in general_ a mu4e user who is in a process of performing customizations has several methods of making the changes active, in order of descending trouble:

- restarting Emacs
- restarting mu4e
- re-fetching mail (`mu4e-update-mail-and-index`, bound to `U`)

There are many, many settings around mu4e, and so it would have been preferrable if effecting the customisations had the following properties:
- was as lightweight as meaningfully possible
- was generic

So, if you take this point of view, perhaps it can be seen that the fact that one has to know a _special_ incantation to effect the `mu4e-maildirs-extension-custom-list` customizations is.. unfortunate.

Of course there could be other considerations that make this view less relevant, but that's what my user experience roughly amounted to.

**Comment by agpchil** [comment]
Sorry, but I have no idea what exactly are you asking for :(

**Comment by deepfire** [comment]
Sorry, perhaps it's too specific an issue, and so not worth keeping open -- closing it provisionally.
