### ISSUE TITLE
mu4e-maildirs-extension-load-bookmarks doesn't work with bookmark queries that are expressions

### ISSUE THREAD

**Issue by andersjohansson** [agpchil/mu4e-maildirs-extension#31]
I just started using the extension. It looks nice!
I see that the bookmarks thing is still experimental and disabled by default, but for some reason, my first run without customising anything (`mu4e-maildirs-extension-use-bookmarks` is nil) runs `mu4e-maildirs-extension-load-bookmarks` which halts with an error:
````Elisp
(wrong-type-argument characterp aj/mu4e-get-all-uu-archives)
````
This is not very surprising since one of my bookmarks is:
````Elisp
((aj/mu4e-get-all-uu-archives)
  "UU-arkiv" 97)
````
(a function that returns all subdirectories in my archive).

`maildirs-extension-load-bookmarks` tries to concat this with `" AND flag:unread"`, which not so surprisingly doesn't work. mu4e supports expressions (that should return a search query) as bookmark definitions. Apperently mu4e-maildirs-extension does not now.

The solution would be to put an eval of `query` somewhere and check that we get a string (like in `mu4e-get-bookmark-query`).

I don't know why `mu4e-maildirs-extension-load-bookmark` is run in the first place though.

**Comment by andersjohansson** [comment]
````Elisp
(defun mu4e-maildirs-extension-load-bookmarks ()
  "Fetch data or load from cache."
  (unless mu4e-maildirs-extension-bookmarks
    (mapc (lambda(it)
            (let ((query (eval (nth 0 it)))
                  (bm (list :data it)))
              (when (stringp query)
                (add-to-list 'mu4e-maildirs-extension-bookmarks bm t)
                (mu4e-maildirs-extension-bm-count bm
                                                  :unread
                                                  (concat query " AND flag:unread"))
                (mu4e-maildirs-extension-bm-count bm :total query))))
          mu4e-bookmarks))
  mu4e-maildirs-extension-bookmarks)
````

This seemed to work kind of, but I don't know if the bookmarks display is really right, it shows all messages for that bookmark as unread:
````
* [ba] UU-arkiv (6141/6141)
````

**Comment by andersjohansson** [comment]
Ah, `mu4e-maildirs-extension-load-bookmarks` is called regardless of `mu4e-maildirs-extension-use-bookmarks` in `mu4e-maildirs-extension-update`. Do the bookmark counts have to be loaded that early? Isn't that unnecessary if they won't be used?

**Comment by agpchil** [comment]
Thanks for your feedback!

The bookmarks feature is a WIP but this looks like a bug to me.

As you said, it makes no sense that `mu4e-maildirs-extension-load-bookmarks` is being called when `mu4e-maildirs-extension-use-bookmarks` is nil.

Can you send a PR if you fixed this issue?
Thank you!
