### ISSUE TITLE
After latest commit, maildirs don't update when new mail arrives

### ISSUE THREAD

**Issue by joostkremers** [agpchil/mu4e-maildirs-extension#34]
Hi,

Up until the latest commit, 0b7908280c97c1fe29de0d10ac2715344e36b1e4, the new mail counts in mu4e's main buffer would be updated after pressing `u` whenever new mail had arrived. Since that commit, however, I find that that is no longer the case. I need to do `C-u C-u u` in order to make sure that the new mail counts are displayed correctly.

I added the value of `mu4e-maildirs-extension-index-updated-function` back to `mu4e-index-updated-hook` and now it works again. Perhaps this should be done unconditionally by `mu4e-maildirs-extension`?

**Comment by agpchil** [comment]
Hi! Thanks for the feedback.

Should we set both msg-changed and index-updated hooks at the same time? /cc @j-hao 

Also, I don't know if it makes sense to have the `C-u u` variants anymore. Since the fetching is done async now and it's quite fast maybe we should make `u` perform the full update and remove the prefixes ones...

**Comment by j-hao** [comment]
index-updated hook will run msg-changed hook internally. Wondering if index-updated hook got called when press `u`? I agree maybe it's better to make `u` to perform full update.

**Comment by j-hao** [comment]
Found the issue. I only added msg-changed hook to index-updated hook within header mode only. Have created a new PR for mu4e to add it globally. Let me know if this fix the issue for you.

**Comment by agpchil** [comment]
@j-hao Thank you for the quick fix! :)
@joostkremers can you confirm if this fix the issue for you?

**Comment by agpchil** [comment]
Well, I'm closing this as it should be fixed already. Feel free to open again otherwise!

**Comment by joostkremers** [comment]
It seems that the variable `mu4e-msg-changed-hook` has been renamed to `mu4e-message-changed-hook`, so commit 0b7908280c97c1fe29de0d10ac2715344e36b1e4 doesn't work anymore.

**Comment by agpchil** [comment]
Sorry @joostkremers. I'd missed your report. 
I reopened this issue to let others know about this.
If anyone fixes this please send a PR!

**Comment by joostkremers** [comment]
From what I can tell by looking at the `mu4e` git log, it's just a simple rename from `mu4e-msg-changed-hook` to `mu4e-message-changed-hook`, so all that should be necessary is to change the name in the `mu4e-maildirs-extension` source as well.

**Comment by tychobrailleur** [comment]
I have opened a PR (#39) for this.  As @joostkremers mentioned, the hook was deprecated and renamed message.

**Comment by agpchil** [comment]
This should be fixed with the PR @tychobrailleur sent. But feel free to reopen or send a new PR otherwise.
Thank you all!
