### ISSUE TITLE
mailboxes do not display properly

### ISSUE THREAD

**Issue by mnsanghvi** [agpchil/mu4e-maildirs-extension#41]
I used to have my `(setq mu4e-maildir "~/Mail")` but have changed it to be `~/Mail/sub-dir` now.  Also I used to set it globally and now I set it as part of my mu4e-context.  After making those changes, and changing the paths to folders to make them relative to the new `mu4e-maildir` setting,  I now get the mailboxes displayed as shown in the attachment below.  The line gaps did not used to exist before.  Any idea on where/how these are getting set ?  I tried looking in the code to determine the cause, but was not able to do so.   Most likely that is due to my poor elisp.

<img width="996" alt="screenshot 2017-05-24 at 23 47 28" src="https://cloud.githubusercontent.com/assets/1726664/26435246/def61a9c-40db-11e7-8c09-934c1e2fc836.png">

**Comment by agpchil** [comment]
The UI glitch you're getting (missing top-level account name, gaps, etc) is probably due to some "wrong" configuration that makes the directory structure to be parsed incorrectly.

I think it's the same issue as #21. Can you follow that thread and see if it works for you?

**Comment by mnsanghvi** [comment]
I read through that thread and here is what I had changed:

My directory layout is as follows:

```
Mail
|--Work
     |--INBOX
     |--Sent
     |--Drafts
     `--Trash
```
 
My original settings that worked are as follows:

```
(setq mu4e-maildir "~/Mail")
(setq mu4e-drafts-folder "/Work/Drafts")
(setq mu4e-sent-folder "/Work/Sent")
(setq mu4e-trash-folder "/Work/Trash")
(setq mu4e-maildir-shortcuts
        '(("/Work/Archive" . ?a)
          ("/Work/Sent"    . ?s)
          ("/Work/Trash"   . ?t)
          ("/Work/Drafts"  . ?d)))
```

And I did the following
```
mu index --maildir=~/Mail
```


Why does it make a difference if I make the following changes:

```
(setq mu4e-maildir "~/Mail/Work")
(setq mu4e-drafts-folder "/Drafts")
(setq mu4e-sent-folder "/Sent")
(setq mu4e-trash-folder "/Trash")
(setq mu4e-maildir-shortcuts
        '(("/Archive" . ?a)
          ("/Sent"    . ?s)
          ("/Trash"   . ?t)
          ("/Drafts"  . ?d)))
```
and than do 
```
mu index --maildir=~/Mail/Work
```

I do not use multiple accounts for work, but I have some other things in `~/Mail` from when I was using Mail.app that I do not want to get indexed, hence the change in the configuration.

**Comment by agpchil** [comment]
This extension expects an extra directory that "simulates an account". In your case, if you setup mu/mu4e to use `~/Mail/Work` then you should have the directory layout like:

```
Mail
|--Work
  |--account
     |--INBOX
     |--Sent
     |--Drafts
     `--Trash
```

Note the extra `account` directory.

I think you will need to clear and re-index the database again if you change the directory layout.

**Comment by mnsanghvi** [comment]
I did that, and things the world is all normal now :)

Now to find out if there is a way to make the Maildirs list be the first item showing up in `*mu4e-main*` buffer,  rather than as the 3rd item.

**Comment by agpchil** [comment]
I'm glad it worked ;)

About the position,  the variable `mu4e-maildirs-extension-insert-before-str` allows you to customize where to insert the maildirs section.

**Comment by mnsanghvi** [comment]
Thanks for the tip.

Issue closed.
