### ISSUE TITLE
emacs 26.3 and new mu 1.3.5

### ISSUE THREAD

**Issue by cryoguy** [agpchil/mu4e-maildirs-extension#50]
Is anybody experiencing any issue with emacs 26 and most recent mu update (1.3.5)?

**Comment by agpchil** [comment]
Last version I tried was emacs 26.3 and mu 1.2.0. But emacs should not crash anyway. 
Does it work without `mu4e-maildirs-extension`?

djcb/mu#1534

**Comment by wedens** [comment]
I don't have any issues with emacs 27, latest mu4e-maildirs-extension and mu 1.3.5.

**Comment by cryoguy** [comment]
I have to uninstall noto-emoji font to fix the issue!
